### ISSUE TITLE
Bug: Possibility to order via DPD Parcelshop without selecting a parcelshop

### ISSUE THREAD

**Issue by d33x** [dpdconnect/prestashop17-shipping#11]
A major bug to be fixed.

It is possible to order and have your order delivered to a parcelshop without selecting the parcelshop. As a result, you get a label in DPD Classic (or Home) when the customer has paid for the parcelshop.

So money is lost.

Step to reproduce the bug (there may be other cases!): 
- Disable javascript and select "DPD ParcelShop".
- Continue
- Pay (if problem to pay, allow again the javascript)

I have tried with other carriers (other than DPD), some refuse to validate the delivery step if javascript is not allowed.

**Comment by dpdplugin** [comment]
Hi @d33x ,

Thank you for the feedback, we will pass it on to the developers for upcoming releases.

**Comment by d33x** [comment]
Hi @dpdplugin @AVHBE

Any news about this major bug?

**Comment by dpdplugin** [comment]
In the coming weeks there will be a new release with the backend functionality revamped, this should fix this.

**Comment by dpdplugin** [comment]
This is fixed in version 1.3.0
