### ISSUE TITLE
Improvement: Add the possibility to automatically change the order status after the label is generated

### ISSUE THREAD

**Issue by d33x** [dpdconnect/prestashop17-shipping#14]
Improvement: Add the possibility to automatically change the order status after the label is generated

Some other modules offer this as **an option** and it is very interesting. This would save time and efficiency.

![dpd-change-order-status](https://user-images.githubusercontent.com/76649472/125650595-d38e2dee-44fb-492d-9208-21d86fe1873f.png)

**Comment by AVHBE** [comment]
Hi @d33x 

This would require an integration with our Parcellifecycleservice via API and its indeed a medium term goal to achieve this type of visiblity in all DPD Benelux plugin's

Thx!

**Comment by d33x** [comment]
Thx

**Comment by dpdplugin** [comment]
Hi @d33x ,

Thank you for the feedback, we will pass it on to the backlog/wishlist.
