### ISSUE TITLE
Improvement: Automatically update the order status to "Delivered" when the order has been delivered - cron job

### ISSUE THREAD

**Issue by d33x** [dpdconnect/prestashop17-shipping#15]
DPD France offers this option but not the Benelux. It would be interesting to have a cron job that changes the status of the order when the package has been delivered.

![dpd-change-order-status](https://user-images.githubusercontent.com/76649472/125650862-b6fe8b7a-a110-4829-bba6-c5ec622559dd.png)

https://addons.prestashop.com/en/shipping-carriers/19414-dpd-france-delivery.html#specifications

**Comment by dpdplugin** [comment]
Hi @d33x ,

Thank you for the feedback, we will pass it on to the backlog/wishlist.
