### ISSUE TITLE
Bug: Tracking numbers are not displayed in the shipping list

### ISSUE THREAD

**Issue by d33x** [dpdconnect/prestashop17-shipping#16]
The correction in #7 does not work. The button works and the shipping list is generated but without the tracking numbers

Here are the different screenshots of the problem.

**In debug mode:**
![bug-dpdshippinglist](https://user-images.githubusercontent.com/76649472/125652377-0180893e-81cc-42d1-ab9d-5e97b8889107.png)

**Without the debug mode:**
![bug-dpdshippinglist-2](https://user-images.githubusercontent.com/76649472/125652430-52b3e392-d876-41c9-b497-9e866947cd49.png)

At the same time, it should be possible to **translate** the shipping list and **add the information** from the DPD Connect shipping list (name of the depot, signature of the deliverer, etc.)

**Comment by AVHBE** [comment]
@dpdplugin 

Can you have a look at this?

**Comment by dpdplugin** [comment]
Hi @d33x ,

Thank you for the feedback, we will pass it on to the developers for upcoming releases.

**Comment by d33x** [comment]
Hi @dpdplugin @AVHBE

Any news about this bug?

**Comment by dpdplugin** [comment]
Hi @d33x,

We expect a new release in the coming weeks with this issue solved.
This release also contains new functionality.

**Comment by dpdplugin** [comment]
This is fixed in version 1.3.0
