### ISSUE TITLE
1.3 : dpdconnect_url is not defined

### ISSUE THREAD

**Issue by d33x** [dpdconnect/prestashop17-shipping#18]
You are using your new API for parcelshop integration, but in some cases the dpdconnect_url is not defined because it is an optional field, which is a problem :

In DpdCheckoutDeliveryStep.php : 
`'dpdParcelshopMapUrl' => Configuration::get('dpdconnect_url') . '/parcelshop/map/js',`

![dpdconnect-db](https://user-images.githubusercontent.com/76649472/144760248-19e79fc2-d49a-4674-a1da-aed7248f2ac7.png)

![dpdconnect-bo](https://user-images.githubusercontent.com/76649472/144760359-f1a8ffc0-34f7-4138-be01-3caca9821cad.png)

![dpdconnect-console](https://user-images.githubusercontent.com/76649472/144760304-22b2549b-825f-4ef5-b7be-1b01577e17d2.png)

**Comment by dpdplugin** [comment]
Hi @d33x,

Thanks for keeping us sharp, we will release a hotfix today!

**Comment by d33x** [comment]
Hi @dpdplugin 

I don't think your correction works because the method does not accept this parameter: https://devdocs.prestashop.com/1.7/development/components/configuration/backward-compatibility/

I use this myself (to maybe optimize):
`'dpdParcelshopMapUrl' => (Configuration::get('dpdconnect_url') ? Configuration::get('dpdconnect_url') : Client::ENDPOINT) . '/parcelshop/map/js',`

**Comment by dpdplugin** [comment]
Hi @d33x ,

We have just compared multiple prestashop versions and in some cases it does accept it, but Prestashop seems to be changing them method often.
Therefore we have changed it to your solution.
