### ISSUE TITLE
Gmap classe isn't working

### ISSUE THREAD

**Issue by cecilehabran** [dpdconnect/prestashop17-shipping#2]
https://github.com/dpdconnect/prestashop17-shipping/blob/203c92696c67f55763ed3f60efd63bb9eb97c0e6/classes/Gmaps.php#L32

This line should be
```php
 $url = "https://maps.googleapis.com/maps/api/geocode/json?key=" . $gmapsKey . "&components=" . $data . '&sensor=false'; 
```

Use "components" instead of "address". 

Now it's working on our store, the map is shown and we can select a pickup point, but once the parcel shop is selected, it's not saved in the order and the delivery address stays the client's address. The selected carrier is correct tho.

**Comment by cleocreations** [comment]
Same problem but the solution proposed by cecilehabran is not working for me.

Any solution?

**Comment by dpdplugin** [comment]
The fix from @cecilehabran is already in the newest version.
It is also important that the maps javascript api + geocoding api are enabled
