### ISSUE TITLE
empty order page

### ISSUE THREAD

**Issue by Juiliard** [dpdconnect/prestashop17-shipping#20]
when customer is clicking on PROCEED TO CHECKOUT button in the Cart(.../en/cart?action=show) - empty page appears with:  HTTP ERROR 500

**Comment by Juiliard** [comment]
1. after installation of dpdcpnneect module v.1.3.1 on fresh PS 1.7.6.5 the following error appear on order page:
2. order page is empty
3. in Debug mode the following errors appear:
<img width="1036" alt="Снимок экрана 2022-01-15 в 19 26 51" src="https://user-images.githubusercontent.com/58143423/149633465-38a2572d-a90c-45e3-adfa-95bc0802b75f.png">
<img width="1040" alt="Снимок экрана 2022-01-15 в 19 27 26" src="https://user-images.githubusercontent.com/58143423/149633484-3359007e-a74c-405d-b9f6-72dc81c94c9f.png">
4. After Deactivate dpdconnect module - order page works good
5. After Uninstall dpdconnect module - the following errors appears:
<img width="954" alt="Снимок экрана 2022-01-15 в 19 32 24" src="https://user-images.githubusercontent.com/58143423/149633645-9a2cbcda-ecd4-45f0-bf2c-99acb6c14603.png">

6. Contacted support team and received the following advise:
_It seems like the overrides are conflicting and thats causing the errors.
You need to manually clean the overrides, unfortunately this is how Prestashop works.
You need to edit the Ordercontroller in the overrides folder controllers/front/OrderController.php and remove the DPD code._

7. I have delete all from controllers/front/OrderController.php - Result of order page:

Fatal error: Uncaught Error: Class 'OrderController' not found in /volume1/Web/classes/controller/Controller.php:219 Stack trace: #0 /volume1/Web/classes/Dispatcher.php(507): ControllerCore::getController('OrderController') #1 /volume1/Web/index.php(28): DispatcherCore->dispatch() #2 {main} thrown in /volume1/Web/classes/controller/Controller.php on line 219

<img width="935" alt="Снимок экрана 2022-01-15 в 20 27 58" src="https://user-images.githubusercontent.com/58143423/149635293-05c0fd17-04ad-4f67-b64e-e42cf0c89812.png">

What else to do to get order works?

PS 1.7.6.5
PHP 7.3

**Comment by dpdplugin** [comment]
The error means your credentials are not correct "an authentication exception occurred".
You can contact your DPD account manager to fix this.
I am deleting this ticket because it contains your credentials.
We will contact you on support.
