### ISSUE TITLE
No translation of your API for parcelshop

### ISSUE THREAD

**Issue by d33x** [dpdconnect/prestashop17-shipping#21]
Thank you for completely rewriting the Parcelshop functionality, but in this case, your version 1.3 module is unusable because it cannot be translated.

We have French, Dutch, English, Spanish and German speaking customers and we end up with a mixture of French, English and Dutch. (see attached screenshots) and even some terms that are poorly translated or look like "selectParcelshop" code.

Your API should also take into account the language of the client!

![parcelshop](https://user-images.githubusercontent.com/76649472/151805005-a68ea5ee-9306-411b-87bc-69cffd2f49bc.png)
![parcelshop-2](https://user-images.githubusercontent.com/76649472/151805001-72cb3e53-6c8f-45f6-9737-581a924860ae.png)
![parcelshop-3](https://user-images.githubusercontent.com/76649472/151805006-af41ece2-9a2e-42ab-8a5e-4bc50113ea78.png)

**Comment by d33x** [comment]
@dpdplugin @AVHBE ?

**Comment by dpdplugin** [comment]
Hi @d33x,

The JS of the map should pass a language code to the Iframe: https://github.com/dpdconnect/prestashop17-shipping/blob/3fd5204969694d900c1a4aeda2bb5bcfb7373f99/views/templates/1.7/_dpdLocator1.7.tpl#L104
So it should take into account the language of the shop.
But it seems its not properly set in your store, if you print the languageCode, what does it show?

**Comment by d33x** [comment]
`<html>
<body>


 
--
<script>
  | const baseUri = "/";
  | const parcelshopId = 34;
  | const sender = 34;
  | const shippingAddress = "Rue de la Croix Limont 8 5109 Belgium";
  | const dpdPublicToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NDU3ODA5NzUsImV4cCI6MTY0NTgwOTc3NSwicm9sZXMiOlsiUk9MRV9DT05ORUNUX0FMTCJdLCJ1c2VybmFtZSI6IktEMTQwMDMzRzkiLCJzY29wZSI6InB1YmxpYyJ9.bWpWWN-n_JCAyMNuVuKGSBqexTo_PSoPSlPZnTexDFrVrP95CT0d0brjPiJ9q-5cEPcDIbXeRve3ixUpAw9mkeAGjGZm2ob32Qr7VeAuoi9cCUHLkI5k-mz36Ha1pDloJGgsN5E7RyxJQ0VmyLNazO5-JOpwUVlSEZzZ7tNNepqOHPmsGw-pn_OBXsby8OE3sMnHCZRuhsq5ln7LNKGFwrjBsqDGC0cG-uNc4PNWeAjQ9iNwzEz0tL04VSfDinv3vWJmTVvDxTutzotJR9LXb1HuDdDzSsDSB-8Yno20OE-Yi4hHhD6NqKMUPGH-1Q8I6OIb46BG8syHGFgoN98XBDoVoqpnxmUMi4ZE83IS4n8H4YIOtj2s8gyu3cdY2FLT1Hl2ZHOwtiQ4r6aSa4w-GcpUFJiv14vpDFlVObuYF_hO8SnAIBLOgRXXhL1DeMiIxhh3U31qQ3Hliei6DR7aZcFlB_hxe_napwzkbfMThGXO2s0WpZxywXqnzAsPrp8rZ6eGCH3o7imbDNFLxdC0Rq7nru8IkfSqSopMdm1VDgYTJWGYyULtZByUFDOWrZlDMNS7Xi8HYd6oAL6lTaA90y86CzE-RFk1pIbRfEtAmKGpFZnfx_ZEX5xmBVVJU9VL98-WFrtt36pGHPYnEffM1IPU0_ai50mTNSMW-salx48";
  | const shopCountryCode = "fr";
  | const mapsKey = "";
  | const cookieParcelId = "666921576";
  | const oneStepParcelshopUrl = "https://prestashop2.m3-group.be/fr/module/dpdconnect/OneStepParcelshop";
  | const dpdParcelshopMapUrl = "https://api.dpdconnect.nl/parcelshop/map/js";
  |  
  | var mapInitialized = false;
  |  
  | document.addEventListener('DOMContentLoaded', function(){
  | jQuery(document).on('ready', function () {
  | $.getScript(dpdParcelshopMapUrl, function() {
  |  
  | DPDConnect.onParcelshopSelected = function (parcelshop) {
  | // Store selected parcelshop
  | jQuery.post(oneStepParcelshopUrl, {
  | 'method': 'setParcelShop',
  | 'parcelId': parcelshop.parcelShopId,
  | 'parcelShopSenderId': parcelshopId,
  | 'sender': sender
  | });
  |  
  | jQuery("#parcel-id").val(parcelshop.parcelShopId);
  | jQuery(".dpd-alert").hide();
  | jQuery(".alert-danger").hide();
  | };
  |  
  | // Loop through every delivery option to see if a DPD Parcelshop carrier is selected
  | jQuery(".delivery-options input").each(function () {
  | if (jQuery("#" + this.id).prop("checked")) {
  |  
  | // Check if DPD Parcelshop carrier is selected
  | if (this.value === parcelshopId + ',') {
  | if (mapInitialized) {
  | showContainer();
  | } else {
  | initMap();
  | }
  | }
  | }
  | });
  |  
  | // Hide or show the parcelshop selector when a different delivery option is selected
  | jQuery('.delivery-options input').on('change', function () {
  | if (this.value === parcelshopId + ',') {
  | if (mapInitialized) {
  | showContainer();
  | } else {
  | initMap();
  | }
  | } else {
  | hideContainer();
  | }
  | });
  |  
  | // On one page checkout, prevent continuing when no parcelshop has been selected
  | jQuery('#opc_payment_methods-content').on('click', 'a', function (e) {
  | jQuery('#opc_delivery_methods input.delivery_option_radio').each(function () {
  | if (jQuery("#" + this.id).prop("checked")) {
  |  
  | // Check if delivery option is a DPD Parcelshop carrier
  | if (this.value === parcelshopId + ',') {
  |  
  | // Show alert when no parcelshop has been chosen
  | if (!jQuery('#parcel-id').val()) {
  | e.preventDefault();
  | jQuery('.dpd-alert').show();
  | }
  | }
  | }
  | });
  | });
  |  
  | // In normal checkout, prevent continuing when no parcelshop has been selected
  | jQuery('#dpd-connect\\\\classes\\\\dpd-checkout-delivery-step .continue').on('click', function(e) {
  | if (jQuery('.delivery-options input:checked').val() == parcelshopId + ',' && !jQuery('#parcel-id').val()) {
  | e.preventDefault();
  | jQuery('.dpd-alert').show();
  | }
  | });
  | });
  | });
  | });
  |  
  | function initMap() {
  | if (mapInitialized) {
  | return;
  | }
  |  
  | addDivs();
  |  
  | // If mapsKey is empty that means user chose to use DPD's key
  | if (mapsKey != '') {
  | DPDConnect.show(dpdPublicToken, shippingAddress, shopCountryCode, mapsKey);
  | } else {
  | DPDConnect.show(dpdPublicToken, shippingAddress, shopCountryCode);
  | }
  |  
  | mapInitialized = true;
  | }
  |  
  | function addDivs() {
  | if(jQuery('#dpd-connect-container').length == 0 ){
  | jQuery('#dpd-connect\\\\classes\\\\dpd-checkout-delivery-step .content .form-fields').append(
  | '<div id="dpd-connect-container"></div>'
  | );
  | }
  | if(jQuery('#dpd-connect-map-container').length == 0 ){
  | jQuery('#dpd-connect-container').append('<div id="dpd-connect-map-container" style="width: 100%; height: 450px;"></div>');
  | }
  | if(jQuery('#dpd-connect-selected-container').length == 0 ){
  | jQuery('#dpd-connect-container').append('<div id="dpd-connect-selected-container" style="display: none;">' +
  | 'Selected parcelshop:<br />\n' +
  | '<strong>%%company%%</strong><br />\n' +
  | '%%street%% %%houseNo%%<br />\n' +
  | '%%zipCode%% %%city%%<br />\n' +
  | '<br \>' +
  | '<a href="#" id="dpd-connect-change-parcelshop" onclick="onParcelshopChange(event)"><strong>Modifier</strong></a>\n' +
  | '</div>');
  |  
  | }
  | }
  |  
  | function onParcelshopChange(event) {
  | // Prevent jumping to top of page when clicking on 'Change' button of selected parcelshop
  | event.preventDefault();
  |  
  | hideSelectedContainer();
  | showMapContainer();
  | }
  |  
  | function showContainer() {
  | jQuery('#dpd-connect-container').show();
  | }
  |  
  | function hideContainer() {
  | jQuery('#dpd-connect-container').hide();
  | }
  |  
  | function showMapContainer() {
  | DPDConnect.getMapContainer().style.display = 'block';
  | }
  |  
  | function hideMapContainer() {
  | DPDConnect.getMapContainer().style.display = 'none';
  | }
  |  
  | function showSelectedContainer() {
  | DPDConnect.getSelectedContainer().style.display = 'block';
  | }
  |  
  | function hideSelectedContainer() {
  | DPDConnect.getSelectedContainer().style.display = 'none';
  | }
  | </script>
  |  


</body>
</html>`

**Comment by d33x** [comment]
Hi @dpdplugin 

https://pastebin.com/QLH0ehHC

**Comment by d33x** [comment]
@dpdplugin I just tried it on a clean PrestaShop installation (1.7.7.8) and I have the same problem. So it's not just my shop

**Comment by dpdplugin** [comment]
@d33x we are investigating the issue and get back to you shortly

**Comment by d33x** [comment]
Any news @dpdplugin ?

**Comment by dpdplugin** [comment]
Hi @d33x , we have released a new version of the API.
It should be fixed now, you might need to refresh your browser cache.

**Comment by d33x** [comment]
Thanks @dpdplugin, I'll be able to consider using version 1.3!
