### ISSUE TITLE
No /vendor/autoload.php error

### ISSUE THREAD

**Issue by tihonnsk** [dpdconnect/prestashop17-shipping#6]
I tried to install the module in PS 1.7.7.3 but got this:
Compile Error: PrestaShop\PrestaShop\Adapter\Module\ModuleDataProvider::main(): Failed opening required '/home/pournop/www/modules/dpdconnect/vendor/autoload.php' (include_path='/home/pournop/www/vendor/pear/pear_exception:/home/pournop/www/vendor/pear/console_getopt:/home/pournop/www/vendor/pear/pear-core-minimal/src:/home/pournop/www/vendor/pear/archive_tar:.:/usr/local/php7.2/lib/php');
After I delete require_once(_PS_MODULE_DIR_ . 'dpdconnect' . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php');
I have error Attempted to load class "DpdHelper" from namespace "DpdConnect\classes".
Did you forget a "use" statement for another namespace?

**Comment by dpdplugin** [comment]
Hi @tihonnsk ,

You are currently trying to install the development build which isn't precompiled, you can download a installable zip from the releases page: https://github.com/dpdconnect/prestashop17-shipping/releases

**Comment by tihonnsk** [comment]
Thanks! Solved.
