### ISSUE TITLE
ShippingList in 1.7.7 no longer works

### ISSUE THREAD

**Issue by d33x** [dpdconnect/prestashop17-shipping#7]
Hello,

Is it possible to solve this problem? It is no longer possible to override the AdminOrdersController, hence the bug.
![21-05-2021 16-42-56](https://user-images.githubusercontent.com/76649472/119155604-a5b3ad80-ba53-11eb-8359-a69b816c48a4.png)

Thank you for the solution!

**Comment by d33x** [comment]
@dpdplugin

**Comment by dpdplugin** [comment]
Hi @d33x ,
We expect to release a new version next week where this is fixed!

**Comment by d33x** [comment]
@dpdplugin any news?

**Comment by d33x** [comment]
@dpdplugin any news?

**Comment by AVHBE** [comment]
Hi @d33x 

Will ask the developers to post an update.
You can also mail the DPD Belux/NL IT service desk to open a follow-up ticket regarding this topic.

Andy Van Hove
DPD Belux PM Shipping Applications

**Comment by dpdplugin** [comment]
Hi @d33x 

We are sorry for the delay, the new version has been published!
