### ISSUE TITLE
Improving translations - _dpdLocator1.7 & _adminOrderTabLabels

### ISSUE THREAD

**Issue by d33x** [dpdconnect/prestashop17-shipping#9]
Version: 1.7.7

I couldn't make a pull request but anyway I think my file needs to be improved (even if it works for me) for older versions perhaps.

There are several translation problems or fields that could not be translated:

**_dpdLocator1.7.tpl**
- More information
- Ship to this parcelshop
- There is 1 error
- Please select a parcelshop

**_adminOrderTabLabels.tpl**
- Print DPD label
- Number of parcels
+ Adding a margin-left

Thanks
[_dpdLocator1.7.txt](https://github.com/dpdconnect/prestashop17-shipping/files/6731989/_dpdLocator1.7.txt)
[_adminOrderTabLabels.txt](https://github.com/dpdconnect/prestashop17-shipping/files/6731990/_adminOrderTabLabels.txt)

**Comment by dpdplugin** [comment]
Thank you for your contribution, they will be considered for the next release
